# -*- coding: utf-8 -*-
"""crawler for the web search for user defined keywords.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PKJ_reTa3xukWgiIK8WJLpnMs-ihp-Ku
"""

import requests
url = 'https://en.wikipedia.org/wiki/Stock_market'

response = requests.get(url, timeout=3) #timeout set to stop the request action in case of hanging
print('Status code: ',response.status_code)
if response.status_code==200:
    print('Connection successfull.\n\n')
else: 
    print('Error. Check status code table.\n\n')

print(f"{'---'*20}\n\tContents of Response.items():\n{'---'*20}")

for k,v in response.headers.items():
  print(f"{k:{25}}: {v:{40}}")

for k,v in response.headers.items():
  print(f"{k}: {v}")

print(f"Status code: {response.status_code}") 
print(f"Status code: {response.status_code:>{20}}") 
print(f"Status code: {response.status_code:->{20}}")

from bs4 import BeautifulSoup
page_content = response.content
soup = BeautifulSoup(page_content,'lxml') #'html.parser')

print(soup.prettify()[:2000])

body = soup.body
for child in body.children:
  print(child if child is not None else ' ', '\n\n')  # '\n\n' for visual separation

title = soup.head.title
print(title.parent.name)

results = soup.find_all()

results

