# -*- coding: utf-8 -*-
"""focused crawler for local search.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Siwqn4ytgP9ltJ9IUn6QbaxvfSfu25fF
"""

import requests
import lxml 
from bs4 import BeautifulSoup

url = "https://www.rottentomatoes.com/top/bestofrt/"
f = requests.get(url)

soup = BeautifulSoup(f.content,'lxml')

movies = soup.find_all('div',{'class':'discovery-tiles__wrap'})[1].find_all('a')

movies_list = []
num = 0
for movie in movies:
  try:
    url = 'https://www.rottentomatoes.com' + movie["href"]
    movie_f = requests.get(url)   
    movie_page = BeautifulSoup(movie_f.content,'html')
    num += 1
    title = movie_page.find('h1', {'class': 'scoreboard__title'})
    movie_content = movie_page.find('div', {'class': 'movie_synopsis'})
    movies_list.append({
        "#": num,
        "url": url,
        "title": title.text,
        "content": movie_content.getText()
    })
  except:
    continue

len(movies_list)

for movie in movies_list[:10]:
  print(f"{movie['#']} \nurl: {movie['url']} \ntitle: {movie['title']} \ncontent: {movie['content']}")

